---
# task file for wildfly

- name: install Wildfly prerequisite
  include_tasks: install-prerequisite.yml

- name: set variables for download
  include_vars: download_wildfly.yml

- name: download Wildfly installer
  include_tasks: download.yml

- name: 'create application directory: {{ wildfly_base }}'
  file:
    path: '{{ wildfly_base }}'
    owner: '{{ wildfly_user }}'
    group: '{{ wildfly_group }}'
    mode: '{{ wildfly_dir_mode }}'
    state: directory

- name: install Wildfly
  include_tasks: install.yml

- name: configure Wildfly
  include_tasks: configure.yml

- include_tasks: ulimits.yml
- include_tasks: users.yml

- include_tasks: ssl.yml
  when: wildfly_enable_ssl

- include_tasks: vault.yml
  when: wildfly_vault_enable

- name: manage firewalld
  include_tasks: manage-firewalld.yml
  when: wildfly_manage_firewalld

- include_tasks: service.yml

- include_tasks: vault-configure.yml
  when: wildfly_vault_enable

- name: delete wildfly tar file
  file:
    path: '{{ wildfly_download_dir }}/{{ wildfly_download_file }}'
    state: absent
  when: not wildfly_installer_keep
